Ecommerce|Akash Gupta|using controller,service and dao
Akashhhhh/InternshipGradle pull request #3
Opened 2021-02-23 06:39 UTC by Akashhhhh

2021-02-24 09:39 UTC, nikhilrss requested changes

2021-02-24 09:39 UTC, nikhil-rss-zs commented on src/main/java/ecommerce/controller/CustomerController.java
> +    public void customer(LruCacheService lru, Connection con) {
avoid repeating code

2021-02-24 09:39 UTC, nikhil-rss-zs commented on src/main/java/ecommerce/controller/OrderController.java
> +            menu = orderDao.menu(con);
product service.getAllProdcuts

2021-03-02 06:32 UTC, nikhilrss requested changes

2021-03-02 06:32 UTC, nikhilrss commented on src/main/java/ecommerce/EcomApp.java
> +    public static void main(String[] args) throws InvalidInputException, ApplicationRuntimeException {
Why is main method throwing Exceptions ?

2021-03-02 06:32 UTC, nikhilrss commented on src/main/java/ecommerce/controller/CustomerController.java
> +            Set<ConstraintViolation<Customer>> constraintViolations = validator.validate(obj);
Validations to be done in the validator class

2021-03-02 06:32 UTC, nikhilrss commented on src/main/java/ecommerce/controller/OrderController.java
> +    OrderDao orderDao = new OrderDao();
Why is orderDao initialized ?

2021-03-02 06:32 UTC, nikhilrss commented on src/main/java/ecommerce/controller/OrderController.java
> +
Menu should be fetched from product service as this a product service functionality

2021-03-02 06:32 UTC, nikhilrss commented on src/main/java/ecommerce/exception/InvalidInputException.java
> +    public InvalidInputException(int errorCode, String errorMessage) {
initialize super(e) as well.

2021-03-02 06:32 UTC, nikhilrss commented on src/main/java/ecommerce/service/CustomerService.java
> +        if (!validator.validateEmailId(email)) {
Keep validation return methods consistent

2021-03-04 06:53 UTC, nikhilrss approved these changes

2021-03-04 06:54 UTC, merged